---
# tasks file for resolvconf

- name: Configure DNS for all ESXi hosts of a cluster
  community.vmware.vmware_host_dns:

    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"


    cluster_name: '{{ vcenter_cluster_name }}'
    type: static
    domain: "{{ search_domain | default (omit) }}" 
    dns_servers: "{{ nameservers }}"
  delegate_to: localhost
