---
# tasks file for resolvconf

- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: nm_config

- name: deploy resolv.conf template
  template:
    src:  resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: resolvconf

- name: reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
  when:  resolvconf.changed or nm_config.changed
    

